# Generated by Codex on 2026-07-06

from django.db import migrations, models


def preserve_existing_batch_scoring(apps, _):
    problem_test_case = apps.get_model('judge', 'ProblemTestCase')
    problem_test_case.objects.filter(type='S').update(batch_scoring='min')


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_add_pac_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcase',
            name='batch_scoring',
            field=models.CharField(
                choices=[('sum', 'Sum'), ('min', 'Min')],
                default='sum',
                help_text=(
                    'How Batch start rows aggregate child cases. '
                    'Sum uses per-case points; Min keeps the existing all-or-nothing batch behavior.'
                ),
                max_length=20,
                verbose_name='batch scoring',
            ),
        ),
        migrations.RunPython(preserve_existing_batch_scoring, migrations.RunPython.noop),
    ]
